/* Generated by Together */

package sgt.sgt.contour;
/**
 * Not implemented.
 */
public class TreeEnumerator implements java.util.Enumeration {
  public boolean hasMoreElements() {
    return false;
  }
  public Object nextElement() {
    return null;
  }
}
